measurement_sources: ["odom", "twist0"]

twist0:
  topic: "/cmd_vel"
  queue_size: 1
  timeout: 0.5
  pose_rejection_threshold: 0.8
  twist_rejection_threshold: 0.5
  pose_covariance_diagonal: [1e-3, 1e-3, 1e-6, 1e-6, 1e-6, 1e-6]
  twist_covariance_diagonal: [1e-2, 1e-2, 1e-2, 1e-6, 1e-6, 1e-6]

odom:
  topic: "/odom"
  queue_size: 1
  timeout: 0.5
  pose_rejection_threshold: 0.8
  twist_rejection_threshold: 0.5
  pose_covariance_diagonal: [1e-3, 1e-3, 1e-6, 1e-6, 1e-6, 1e-6]
  twist_covariance_diagonal: [1e-2, 1e-2, 1e-2, 1e-6, 1e-6, 1e-6]